### ISSUE TITLE
Task 2.2 Grading for MDA Milestone 1

### ISSUE THREAD

**Issue by raveenbadyal** [stat545ubc-2023/mda-raveenbadyal#1]
Hi,

I was looking at the rubric for my mda milestone 1 submsission and I noticed that there is a --/4 for Task 2.2. It seems as if my mark for that task is missing because I'd assume there would be a 0/4 if I didn't receive marks for that task. I completed that task for each of the 4 questions I chose to work on in Task 2.1. Thank you in advance for clarifying this for me.

Raveen

**Comment by ErickNavarroD** [comment]
Hi! Sorry about that. I updated your grade (:

**Comment by raveenbadyal** [comment]
Thanks!
